[package]
name = "gr-trace"
version = "0.1.0"
authors = ["Sean Purcell <me@seanp.xyz>"]

[profile.dev]
opt-level = 2

[dependencies]
glium = "0.13.5"
image = "0.7.0"
time = "0.1.34"
clap = "2.1.2"
cgmath = "0.7.0"

